package me.moirai.storyengine.common.enums;

public enum NotificationKind {

    ADVENTURE_INVITE,
    ADVENTURE_INVITE_RESPONSE,
    ADVENTURE_MEMBER_LEFT,
    ADVENTURE_MEMBER_REMOVED,
    ADVENTURE_CHARACTER_DELETED,
    WORLD_ACCESS_GRANTED,
    WORLD_ACCESS_LEVEL_CHANGED,
    WORLD_ACCESS_REVOKED,
    ADVENTURE_ACCESS_GRANTED,
    ADVENTURE_ACCESS_LEVEL_CHANGED,
    ADVENTURE_ACCESS_REVOKED
}
