networks:
  ? moirai_network
services:
  postgresql:
    restart: always
    container_name: postgresql
    hostname: postgresql
    image: postgres:15-alpine
    networks:
      - moirai_network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: moirai
      POSTGRES_PASSWORD: moirai
      POSTGRES_DB: moirai
  moirai:
    container_name: moirai
    hostname: moirai
    image: moirai:latest
    depends_on:
      - postgresql
    networks:
      - moirai_network
    ports:
      - "8080:8080"
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DISCORD_BOT_CLIENT_ID: CHANGE_THIS_VALUE
      DISCORD_BOT_CLIENT_SECRET: CHANGE_THIS_VALUE
      DISCORD_BOT_REDIRECT_URL: http://localhost:8080/auth/code
      DISCORD_BOT_API_TOKEN: CHANGE_THIS_VALUE
      OPENAI_API_TOKEN: CHANGE_THIS_VALUE
      SPRING_APPLICATION_PROFILES: default
      POSTGRES_HOST: postgresql:5432
      POSTGRES_DB: moirai
      POSTGRES_USER: moirai
      POSTGRES_PASSWORD: moirai
      CHATRPG_LOG_LEVEL: INFO