moirai:
  config:
    request-moderation: true
  storage:
    endpoint: ${S3_ENDPOINT}
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    bucket: ${S3_BUCKET}
    region: ${S3_REGION}
  image-generation:
    model: gpt-image-1
    quality: medium
  discord:
    oauth:
      client-id: ${DISCORD_BOT_CLIENT_ID}
      client-secret: ${DISCORD_BOT_CLIENT_SECRET}
      redirect-url: ${DISCORD_BOT_REDIRECT_URL}
    api:
      base-url: ${DISCORD_API_BASE_URL:https://discord.com/api}
      token-uri: /oauth2/token
      token-revoke-uri: /oauth2/token/revoke
      users-uri: /users/%s
  openai:
    api:
      token: ${OPENAI_API_TOKEN}
      base-url: https://api.openai.com
      moderation-uri: /v1/moderations
      responses-uri: /v1/responses
      embeddings-uri: /v1/embeddings
      image-uri: /v1/images/generations
    models:
      embedding: text-embedding-3-small
  qdrant:
    host: ${QDRANT_HOST}
    port: ${QDRANT_PORT}
  rag:
    lorebook:
      top-k: 15
      collection-name: lorebook
      vector-size: 1536
    chronicle:
      top-k: 15
      collection-name: chronicle
      vector-size: 1536
    player-character:
      top-k: 5
      collection-name: player-character
      vector-size: 1536
  adventure:
    message-window-size: ${ADVENTURE_MESSAGE_WINDOW_SIZE:100}
  security:
    allowed-origins: ${ALLOWED_ORIGINS}
    allowed-headers: ${ALLOWED_HEADERS}
    redirect-path:
      success: ${AUTH_SUCCESS_REDIRECT_URL}
      fail: ${AUTH_FAIL_REDIRECT_URL}
      logout: ${AUTH_LOGOUT_REDIRECT_URL}
    unsecured-paths: >
      /auth/code,
      /api/swagger/webjars/swagger-ui/index.html,
      /api/swagger/webjars/swagger-ui/index.css,
      /api/swagger/webjars/swagger-ui/swagger-ui.css,
      /api/swagger/webjars/swagger-ui/swagger-ui-bundle.js,
      /api/swagger/webjars/swagger-ui/swagger-ui-standalone-preset.js,
      /api/swagger/webjars/swagger-ui/swagger-initializer.js,
      /api/swagger/webjars/swagger-ui/favicon-32x32.png,
      /api/swagger/webjars/swagger-ui/favicon-16x16.png,
      /api/swagger/api-docs/swagger-config,
      /api/swagger/api-docs

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    show-sql: false
    properties.hibernate.format_sql: true
  main.banner-mode: off
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  liquibase:
    enabled: true
    defaultSchema: public
    change-log: classpath:db/changelog/changelog-master.xml

logging:
  level:
    me.moirai: ${MOIRAI_LOG_LEVEL:INFO}
    root: ERROR
    org.hibernate: ERROR
    com.zaxxer.hikari: ERROR
    org.springframework: ERROR
    ch.qos.logback: ERROR

springdoc:
  api-docs.path: /api/swagger/api-docs
  swagger-ui.path: /api/swagger/index.html
