moirai:
  nano-id:
    alphabet: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ
    characters-amount: 10
  discord:
    oauth:
      client-id: ${DISCORD_BOT_CLIENT_ID}
      client-secret: ${DISCORD_BOT_CLIENT_SECRET}
      redirect-url: ${DISCORD_BOT_REDIRECT_URL}
    api:
      token: ${DISCORD_BOT_API_TOKEN}
      base-url: https://discord.com/api
      token-uri: /oauth2/token
      token-revoke-uri: /oauth2/token/revoke
      users-uri: /users/%s
  openai:
    api:
      token: ${OPENAI_API_TOKEN}
      base-url: https://api.openai.com
      moderation-uri: /v1/moderations
      completions-uri: /v1/chat/completions
  security:
    ignored-paths: >
      /auth/code,
      /webjars/swagger-ui/index.html,
      /webjars/swagger-ui/index.css,
      /webjars/swagger-ui/swagger-ui.css,
      /webjars/swagger-ui/swagger-ui-bundle.js,
      /webjars/swagger-ui/swagger-ui-standalone-preset.js,
      /webjars/swagger-ui/swagger-initializer.js,
      /webjars/swagger-ui/favicon-32x32.png,
      /webjars/swagger-ui/favicon-16x16.png,
      /v3/api-docs/swagger-config,
      /v3/api-docs

spring:
  profiles.active: ${SPRING_APPLICATION_PROFILES:default}
  main.banner-mode: off
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  liquibase:
    enabled: true
    defaultSchema: public
    change-log: classpath:db/changelog/changelog-master.xml
  security:
    oauth2:
      client:
        registration:
          discord:
            client-name: Discord
            client-id: ${DISCORD_BOT_CLIENT_ID}
            client-secret: ${DISCORD_BOT_CLIENT_SECRET}
            redirect-uri: ${DISCORD_BOT_REDIRECT_URL}
            scope: identify
            client-authentication-method: none
            authorization-grant-type: authorization_code
        provider:
          discord:
            authorization-uri: https://discord.com/api/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/users/@me
            user-name-attribute: id

logging:
  level:
    me.moirai: ${CHATRPG_LOG_LEVEL:INFO}
    root: ERROR
    org.hibernate: ERROR
    com.zaxxer.hikari: ERROR
    discord4j: ERROR
    org.springframework: ERROR
    ch.qos.logback: ERROR
