moirai:
  nano-id:
    alphabet: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ
    characters-amount: 10
  discord:
    bot:
      status: Writing stories, inspiring adventures.
      commands:
        go:
          before-running: >
            The loom spins again — let us continue the tale's weave.,
            Forward, adventurer! The story awaits your next turn.,
            Another thread in the tapestry of your legend begins now.,
            Let's see where the spindle guides us next.,
            The weave continues — new paths beckon ahead.,
            The thread of fate moves forward — let us weave the next chapter.,
            Onward, adventurer! Your journey unfolds anew.,
            Destiny awaits — what lies ahead in the tapestry of your tale?,
            Another step, another story. Let's see what the loom reveals.,
            Forward we march, into the narrative unknown.
          after-running: >
            The tapestry grows richer — your story continues to unfold.,
            A new chapter emerges, woven by the spindle of fate.,
            The loom hums softly — another strand has been added.,
            Your tale takes shape; the next thread is ready.,
            A new scene unfurls, guided by destiny's hand.,
            The weave tightens, revealing the next piece of the puzzle.,
            The story advances — what wonders lie ahead?,
            A fresh thread in the grand design has been spun.,
            The wheel has turned; the narrative grows deeper.,
            The loom whispers softly: your story marches on.
        retry:
          before-running: >
            The loom rewinds, ready to spin a better thread.,
            Let's reshape the pattern — another attempt, another chance.,
            Fate revisited. Let's weave a fresh strand.,
            Not all threads are perfect. A new one begins now.,
            The spindle turns once more; let's craft a finer moment.,
            A tangled thread? Let's unravel and try again.,
            The spindle rewinds — your story deserves another twist.,
            Fate allows second chances — let's craft a better path.,
            Not satisfied? The loom is ready to spin anew.,
            The pattern shifts — another attempt begins.
          after-running: >
            The thread is re-spun; a new path emerges.,
            The spindle rewinds — your story has shifted anew.,
            A fresh pattern appears, untangled and refined.,
            Destiny has rewritten this chapter; see what unfolds.,
            The weave adjusts — another chance to shape your fate.,
            The design evolves; a new attempt takes its place.,
            The tangled threads are smoothed — your tale resets.,
            A better thread is woven, rewriting the tale's course.,
            The loom's hum changes — an improved path has begun.,
            A new draft of fate's design is now complete.
        start:
          before-running: >
            The loom hums to life — your adventure begins here.,
            Welcome to the spindle of fate — let's weave your tale.,
            The first thread is cast — your journey unfolds.,
            Every tale starts somewhere. Here, your legend begins.,
            The loom is ready, the threads await—let's create your saga.,
            The loom is set, and your tale begins to take shape.,
            The journey of a thousand stories begins here.,
            Welcome, weaver of worlds. The threads are yours to guide.,
            Every epic begins with a single spin of the spindle. Let's begin.,
            The pattern emerges — your adventure is about to begin.
          after-running: >
            The spindle spins; your adventure begins now.,
            A fresh tale begins, woven just for you.,
            The loom springs to life — your journey is set.,
            The first thread has been cast; the story awakens.,
            The foundation is laid; your legend begins.,
            Destiny beckons—the opening act is ready.,
            The loom sings of beginnings — your saga starts here.,
            A spark ignites the tale — your journey begins!,
            The story is alive — step into the woven world.,
            The fates smile as your adventure takes its first breath.
    oauth:
      client-id: ${DISCORD_BOT_CLIENT_ID}
      client-secret: ${DISCORD_BOT_CLIENT_SECRET}
      redirect-url: ${DISCORD_BOT_REDIRECT_URL}
    api:
      token: ${DISCORD_BOT_API_TOKEN}
      base-url: https://discord.com/api
      token-uri: /oauth2/token
      token-revoke-uri: /oauth2/token/revoke
      users-uri: /users/%s
  openai:
    api:
      token: ${OPENAI_API_TOKEN}
      base-url: https://api.openai.com
      moderation-uri: /v1/moderations
      completions-uri: /v1/chat/completions
  security:
    ignored-paths: >
      /auth/code,
      /webjars/swagger-ui/index.html,
      /webjars/swagger-ui/index.css,
      /webjars/swagger-ui/swagger-ui.css,
      /webjars/swagger-ui/swagger-ui-bundle.js,
      /webjars/swagger-ui/swagger-ui-standalone-preset.js,
      /webjars/swagger-ui/swagger-initializer.js,
      /webjars/swagger-ui/favicon-32x32.png,
      /webjars/swagger-ui/favicon-16x16.png,
      /v3/api-docs/swagger-config,
      /v3/api-docs

spring:
  jpa:
    show-sql: false
    properties.hibernate.format_sql: true
  profiles.active: ${SPRING_APPLICATION_PROFILES:default}
  main.banner-mode: off
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  liquibase:
    enabled: true
    defaultSchema: public
    change-log: classpath:db/changelog/changelog-master.xml
  security:
    oauth2:
      client:
        registration:
          discord:
            client-name: Discord
            client-id: ${DISCORD_BOT_CLIENT_ID}
            client-secret: ${DISCORD_BOT_CLIENT_SECRET}
            redirect-uri: ${DISCORD_BOT_REDIRECT_URL}
            scope: identify
            client-authentication-method: none
            authorization-grant-type: authorization_code
        provider:
          discord:
            authorization-uri: https://discord.com/api/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/users/@me
            user-name-attribute: id

logging:
  level:
    me.moirai: ${CHATRPG_LOG_LEVEL:INFO}
    root: ERROR
    org.hibernate: ERROR
    com.zaxxer.hikari: ERROR
    net.dv8tion: ERROR
    org.springframework: ERROR
    ch.qos.logback: ERROR
