package me.moirai.storyengine.common.security.authorization;

public enum AuthorizationOperation {
    UPDATE_PERSONA,
    DELETE_PERSONA,
    VIEW_PERSONA,

    UPDATE_WORLD,
    DELETE_WORLD,
    VIEW_WORLD,

    UPDATE_ADVENTURE,
    DELETE_ADVENTURE,
    VIEW_ADVENTURE,
    PLAY_ADVENTURE,
    INVITE_TO_ADVENTURE,
    DECLINE_ADVENTURE_INVITATION,
    JOIN_ADVENTURE_WITH_CHARACTER,
    REMOVE_CHARACTER_FROM_ADVENTURE,

    MANAGE_USER,
    UPDATE_USER_USERNAME,
    UPDATE_USER_ROLE,

    MANAGE_NOTIFICATION,
    VIEW_NOTIFICATION,

    VIEW_PLAYER_CHARACTER,
    UPDATE_PLAYER_CHARACTER,
    DELETE_PLAYER_CHARACTER,
    VIEW_PLAYER_CHARACTER_ADVENTURES
}
