name: Java CI
on: [push, workflow_dispatch]
jobs:
  MoirAI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
      - name: Build
        run: |
            git pull
            mvn package -DskipTests -e
            echo "CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
      - name: Format code to pattern
        uses: actions-js/push@master
        with:
          message: "Automated commit: fix code style according to format"
          branch: ${{ env.CURRENT_BRANCH }}
          author_email: 'github-actions[bot]@users.noreply.github.com'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Unit tests
        if: github.ref != 'refs/heads/main'
        run: mvn test -e
      - name: Unit tests & SonarCloud reports
        if: github.ref == 'refs/heads/main'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn verify sonar:sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }} -e
      - name: Test container build image
        if: github.ref != 'refs/heads/main'
        run: docker build -t registry.gitlab.com/thaalesalves/chatrpg:back-end .
      - name: Build and push image to GitLab Container Registry
        if: github.ref == 'refs/heads/main'
        run: |
          echo ${{ secrets.GITLAB_ACCESS_TOKEN }} | docker login registry.gitlab.com -u thaalesalves --password-stdin
          docker build -t registry.gitlab.com/thaalesalves/chatrpg:back-end .
          docker push registry.gitlab.com/thaalesalves/chatrpg:back-end
