name: Deploy to Digital Ocean
on:
  push:
    tags:
      - '**'
  workflow_dispatch:
jobs:
  MoirAI:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout tag
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Extract MoirAI tag version
        run: |
            echo "LATEST_VERSION_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV
            git checkout $LATEST_VERSION_TAG
            echo Releasing version $LATEST_VERSION_TAG
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ vars.DOCKER_REPO_ADDR }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image to GitHub Container Registry
        run: |
          docker build -t ${{ vars.DOCKER_REPO_ADDR }}/${{ vars.DOCKER_REPO }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.LATEST_VERSION_TAG }} .
          docker push ${{ vars.DOCKER_REPO_ADDR }}/${{ vars.DOCKER_REPO }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.LATEST_VERSION_TAG }}
      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
              echo ${{ secrets.GITHUB_TOKEN }} | sudo docker login ${{ vars.DOCKER_REPO_ADDR }} -u ${{ github.actor }} --password-stdin
              sudo docker rm -f ${{ vars.DOCKER_CONTAINER_NAME }}
              sudo docker rmi $(sudo docker images -q ${{ vars.DOCKER_REPO_ADDR }}/${{ vars.DOCKER_REPO }}/${{ vars.DOCKER_IMAGE_NAME }})
              sudo docker run -d \
                --name ${{ vars.DOCKER_CONTAINER_NAME }} \
                --hostname ${{ vars.DOCKER_CONTAINER_HOSTNAME }} \
                --network ${{ vars.DOCKER_CONTAINER_NETWORK }} \
                -e DISCORD_BOT_REDIRECT_URL=${{ vars.DISCORD_BOT_REDIRECT_URL }} \
                -e DISCORD_BOT_CLIENT_ID=${{ secrets.DISCORD_BOT_CLIENT_ID }} \
                -e DISCORD_BOT_CLIENT_SECRET=${{ secrets.DISCORD_BOT_CLIENT_SECRET }} \
                -e DISCORD_BOT_API_TOKEN=${{ secrets.DISCORD_BOT_API_TOKEN }} \
                -e OPENAI_API_TOKEN=${{ secrets.OPENAI_API_TOKEN }} \
                -e SPRING_APPLICATION_PROFILES=${{ vars.SPRING_APPLICATION_PROFILES }} \
                -e POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} \
                -e POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
                -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
                -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
                -e MOIRAI_LOG_LEVEL=${{ vars.MOIRAI_LOG_LEVEL }} \
                -p 8080:8080 \
                ${{ vars.DOCKER_REPO_ADDR }}/${{ vars.DOCKER_REPO }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.LATEST_VERSION_TAG }}
