name: Build MoirAI on push
on:
  push:
    branches:
      - '**'
  workflow_dispatch:
jobs:
  MoirAI:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
      - name: Build
        run: |
            git pull
            mvn package -DskipTests -e
            echo "CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
      - name: Format code to pattern
        uses: actions-js/push@master
        with:
          message: "Automated commit: fix code style according to format"
          branch: ${{ env.CURRENT_BRANCH }}
          author_email: 'github-actions[bot]@users.noreply.github.com'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Unit tests
        if: github.ref != 'refs/heads/develop' && github.ref != 'refs/heads/master'
        run: mvn test -e
      - name: Unit tests & SonarCloud reports
        if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn verify sonar:sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }} -e
      - name: Test container build image
        if: github.ref != 'refs/heads/develop'
        run: docker build -t registry.gitlab.com/thaalesalves/moirai-be:bleeding-edge .
      - name: Login to GitHub Container Registry
        if: github.ref == 'refs/heads/develop'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build and push image to GitHub Container Registry
        if: github.ref == 'refs/heads/develop'
        run: |
          docker build -t ghcr.io/moirairpg/moirai:bleeding-edge .
          docker push ghcr.io/moirairpg/moirai:bleeding-edge
